# Java Spring Boot Application Name
spring.application.name=pbswarn-alerts

# Database Configurations
spring.data.mongodb.uri=mongodb+srv://jnguy136:fxFGpJ6mOqq23sa2@pbs-warn-alerts.yqnkaqu.mongodb.net/PBS-Warn-Alerts
spring.data.mongodb.database=PBS-Warn-Alerts
spring.data.mongodb.auto-index-creation=true

# Error Handling Configurations
server.error.include-message=always
