services:
  scraper:
    build:
      context: ..
      dockerfile: Dockerfile
    network_mode: service:tailscale
    volumes:
      - ../pbs_warn_outputs:/app/pbs_warn_outputs
    depends_on:
      - tailscale

  tailscale:
    image: tailscale/tailscale:latest
    hostname: pbs-warn-scraper
    environment:
      - TS_AUTHKEY=tskey-auth-kH5hj89nTw11CNTRL-Cs1md1ZgogQ4GgiR8udDgQBxwrd1sF4i
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ts_state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped

volumes:
  ts_state:
